name: Build Komeify App (Nuitka - High Security)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # BẮT BUỘC cài thêm zstandard để Nuitka có thể nén file thành Onefile
        pip install nuitka zstandard 

    - name: Build Application
      shell: bash 
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
            echo "Bắt đầu build cho Windows bằng Nuitka..."
            python -m nuitka \
              --assume-yes-for-downloads \
              --standalone \
              --onefile \
              --enable-plugin=pyqt6 \
              --nofollow-import-to=yt_dlp.extractor.lazy_extractors \
              --include-package=yt_dlp \
              --output-filename=Komeify.exe \
              main.py
            
        elif [ "$RUNNER_OS" == "macOS" ]; then
          echo "Bắt đầu build cho macOS bằng PyInstaller..."
          # Cài PyInstaller riêng cho Mac
          pip install pyinstaller
          # Đóng gói bằng PyInstaller (hỗ trợ PyQt6 trên Mac cực tốt)
          pyinstaller --clean --windowed --name "Komeify" main.py
        fi

    - name: Upload Windows Artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        iss-path: installer.iss

    - name: Upload macOS Artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Komeify-macOS-App
        # Vì dùng PyInstaller, file xuất ra sẽ nằm trong thư mục dist/
        path: dist/Komeify.app